### ISSUE TITLE
iframe support?

### ISSUE THREAD

**Issue by thijselblaso** [galloween/custom-sidebar-v2#1]
Hi, is it possible to show this is an iframe, in the same way as the iframe panel support from Home Assistant?

    {
      "new_item": true,
      "item": "Google",
      "href": "https://mrdoob.com/projects/chromeexperiments/google-gravity/",
      "icon": "mdi:earth",
      "target": "_blank"
    },

**Comment by galloween** [comment]
if you use home assistant's panel_iframe feature in `configuration.yaml`
```
panel_iframe:
  router:
    title: "Router"
    url: "http://192.168.1.1"
  fridge:
    title: "Fridge"
    url: "http://192.168.1.5"
    icon: mdi:fridge
```
then you can reorder iframe links, same as regular ones:
```
{
  "item": "fridge",
},
{
  "item": "lovelace",
},
{
  "item": "router",
},
```
