### ISSUE TITLE
Not working on latest HassOS

### ISSUE THREAD

**Issue by fischer-felix** [galloween/custom-sidebar-v2#19]
Hi, just stumbled across your project and installed it using HACS.

This is my config/configuration.yml
```
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/custom-sidebar-v2/custom-sidebar-v2.js
```
and this my config/www/sidebar-order.json
```
{
    "order": [
    {
      "new_item": true,
      "item": "Google",
      "href": "https://mrdoob.com/projects/chromeexperiments/google-gravity/",
      "icon": "mdi:earth",
      "target": "_blank",
      "order": 4
    },
    {
        "item": "media-browser"
        "hide": true
    }
    ],
    "exceptions": [
    {
        "user": ["eltern"],
        "order": [
        {
            "item": "history",
            "hide": true
        }
        ]
    }
    ]
 }
```

Restarting the server and hard reloading with cache cleaning does not show any results, neither on the main account nor on the user account.
Am I missing some step here or is there any way I could troubleshoot this?
